services:
  db:
    image: postgres:15
    container_name: workoutDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data:rw